### ISSUE TITLE
JWT in cookies?

### ISSUE THREAD

**Issue by mpoisot** [eparreno/rack-jwt#12]
Is there an easy way to have rack-jwt read the token from cookies headers instead of just Bearer?

I [read](https://security.stackexchange.com/a/122991/7473) [several](https://security.stackexchange.com/questions/151884/rest-api-authentication-with-jwt-and-csrf-protection-for-spa) [articles](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage) and discussions about where to store securely JWTs, and it appears the consensus is don't store in localstorage, instead use cookies with secure flags.

**Comment by nashby** [comment]
closed by #32
